import { Business, Agent, ServiceItem, KnowledgeItem, Appointment, Lead, CallLog, Campaign, WidgetConfig, IndustryConfig } from '@/types';

export const INDUSTRIES: Record<string, IndustryConfig> = {
  healthcare: {
    id: 'healthcare',
    name: 'Hospitals & Medical Clinics',
    icon: 'Hospital',
    description: 'Patient triage, appointment scheduling, doctor consultations, insurance checks, and urgent transfers.',
    badge: 'Healthcare Compliant',
    defaultGreeting: 'Thank you for calling St. Jude Regional Clinic. My name is Maya, your AI health assistant. How may I assist your medical care today?',
    defaultPrompt: 'You are Maya, a professional, empathetic, and HIPAA-aware AI medical receptionist for St. Jude Regional Clinic. Help patients book doctor appointments, check clinic hours, explain consultation fees, provide general information about departments, and immediately offer transfer for life-threatening emergencies.',
    sampleServices: [
      { name: 'General Practitioner Consultation', durationMinutes: 30, price: 95, category: 'Outpatient' },
      { name: 'Cardiology Assessment', durationMinutes: 45, price: 180, category: 'Specialist' },
      { name: 'Pediatric Wellness Checkup', durationMinutes: 30, price: 85, category: 'Pediatrics' },
      { name: 'Comprehensive Blood Work & Lab Panel', durationMinutes: 15, price: 65, category: 'Diagnostics' },
      { name: 'Digital X-Ray & Imaging', durationMinutes: 20, price: 120, category: 'Diagnostics' },
    ],
    sampleFaqs: [
      { question: 'What are your emergency procedures?', answer: 'For severe emergencies like chest pain or breathing difficulties, please hang up and dial 911 immediately or proceed to our 24/7 ER on 1400 Health Plaza.', category: 'urgent_protocol' },
      { question: 'Do you accept major health insurances?', answer: 'Yes! We accept BlueCross, Aetna, UnitedHealthcare, Medicare, and Cigna. Co-pays can be handled at check-in.', category: 'pricing' },
      { question: 'Where is patient parking located?', answer: 'Free patient parking is available in the North Parking Structure right next to the Main Clinic entrance.', category: 'location' },
    ],
  },
  real_estate: {
    id: 'real_estate',
    name: 'Real Estate & Property Agencies',
    icon: 'Home',
    description: 'Lead qualification, property inquiries, private tour bookings, pricing estimates, and agent routing.',
    badge: 'High Conversion',
    defaultGreeting: 'Hello! You’ve reached Apex Prime Luxury Real Estate. I am Sophia, your AI concierge. Are you looking to buy, sell, or schedule a VIP private property viewing today?',
    defaultPrompt: 'You are Sophia, an upscale, articulate AI leasing and sales agent for Apex Prime Real Estate. You qualify prospective buyers/renters on budget, target neighborhoods, timeline, and schedule private on-site showings.',
    sampleServices: [
      { name: 'Private Luxury Villa Tour', durationMinutes: 60, price: 0, category: 'Showings' },
      { name: 'Penthouse & Condo VIP Viewing', durationMinutes: 45, price: 0, category: 'Showings' },
      { name: 'Home Valuation & Seller Strategy', durationMinutes: 30, price: 0, category: 'Consultations' },
      { name: 'Commercial Property Acquisition Briefing', durationMinutes: 60, price: 150, category: 'Commercial' },
    ],
    sampleFaqs: [
      { question: 'What luxury neighborhoods do you specialize in?', answer: 'We specialize in Beverly Hills, Bel-Air, Downtown Penthouse Districts, and Newport Coastal estates.', category: 'faq' },
      { question: 'How can I schedule a private tour?', answer: 'I can reserve a private guided tour for you with one of our licensed senior brokers today.', category: 'faq' },
    ],
  },
  auto_repair: {
    id: 'auto_repair',
    name: 'Auto Repair & Performance Shops',
    icon: 'Wrench',
    description: 'Service diagnostics booking, oil change scheduling, tire replacement quotes, status checks.',
    badge: 'Automotive Ready',
    defaultGreeting: 'Thanks for calling Precision Auto Care! I’m Alex, your AI service advisor. Need to schedule maintenance, diagnostics, or check on a repair status?',
    defaultPrompt: 'You are Alex, an expert, friendly AI service advisor at Precision Auto Care. You assist drivers with scheduling oil changes, brake inspections, engine diagnostics, and tire services.',
    sampleServices: [
      { name: 'Synthetic Oil & Filter Service', durationMinutes: 45, price: 89, category: 'Maintenance' },
      { name: 'Complete Brake Pad & Rotor Inspection', durationMinutes: 60, price: 149, category: 'Brakes' },
      { name: 'Computerized OBD-II Engine Diagnostics', durationMinutes: 30, price: 110, category: 'Diagnostics' },
      { name: 'Wheel Alignment & Tire Rotation', durationMinutes: 45, price: 79, category: 'Tires' },
      { name: 'AC Refrigerant Recharge & Cooling Check', durationMinutes: 60, price: 165, category: 'Climate' },
    ],
    sampleFaqs: [
      { question: 'Do you offer warranty on repairs?', answer: 'Yes, all parts and labor come backed by our 24-Month or 24,000-Mile Nationwide Peace of Mind Warranty.', category: 'policy' },
      { question: 'Do you provide loaner vehicles or Uber shuttles?', answer: 'Yes! We provide complimentary Uber rides within 10 miles for services exceeding 2 hours.', category: 'faq' },
    ],
  },
  dental: {
    id: 'dental',
    name: 'Dental Clinics & Orthodontics',
    icon: 'Sparkles',
    description: 'Routine teeth cleanings, emergency toothache triage, cosmetic consultations, Invisalign appointments.',
    badge: 'Dental Focused',
    defaultGreeting: 'Welcome to Lumina Dental Studio. I’m Chloe, your AI receptionist. Are you calling for a routine cleaning, cosmetic consult, or an urgent dental appointment?',
    defaultPrompt: 'You are Chloe, a warm, reassuring AI receptionist for Lumina Dental Studio. Assist patients with scheduling appointments, explaining treatments, and soothing dental anxiety.',
    sampleServices: [
      { name: 'Comprehensive Exam & Deep Cleaning', durationMinutes: 45, price: 120, category: 'Hygiene' },
      { name: 'Invisalign & Orthodontic Consultation', durationMinutes: 30, price: 0, category: 'Cosmetic' },
      { name: 'Laser Teeth Whitening Session', durationMinutes: 60, price: 299, category: 'Cosmetic' },
      { name: 'Emergency Tooth Pain Assessment', durationMinutes: 30, price: 140, category: 'Emergency' },
    ],
    sampleFaqs: [
      { question: 'Do you do same-day emergency appointments?', answer: 'Yes, we reserve morning and afternoon emergency slots daily for acute toothaches or chipped teeth.', category: 'faq' },
      { question: 'Is sedation dentistry available?', answer: 'We offer nitrous oxide and mild oral sedation for nervous patients to ensure complete comfort.', category: 'policy' },
    ],
  },
  retail: {
    id: 'retail',
    name: 'Local Shops, Boutiques & Restaurants',
    icon: 'Store',
    description: 'Opening hours, product inquiries, VIP reservations, catering orders, customer service.',
    badge: 'Local Commerce',
    defaultGreeting: 'Hi! You’ve reached Velvet & Oak Artisan Bakery and Bistro. I’m Liam, your virtual assistant. Can I help with table reservations, custom cake orders, or our daily specials?',
    defaultPrompt: 'You are Liam, a polite and helpful assistant for Velvet & Oak Bistro. You handle table bookings, private event inquiries, dietary questions, and gift card purchases.',
    sampleServices: [
      { name: 'Chef’s Tasting Table (Party of 2-4)', durationMinutes: 90, price: 85, category: 'Dining' },
      { name: 'Custom Wedding & Birthday Cake Tasting', durationMinutes: 45, price: 45, category: 'Bakery' },
      { name: 'Private Rooftop Event Consultation', durationMinutes: 30, price: 0, category: 'Catering' },
    ],
    sampleFaqs: [
      { question: 'Do you offer gluten-free and vegan options?', answer: 'Yes! Over 40% of our daily pastry selection and dinner entrees are certified gluten-free or 100% plant-based.', category: 'faq' },
      { question: 'What is your reservation cancellation policy?', answer: 'Cancellations made at least 6 hours in advance receive a 100% refund with zero penalties.', category: 'policy' },
    ],
  },
};

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz_healthcare_01',
    name: 'St. Jude Regional Clinic',
    slug: 'st-jude-clinic',
    industry: 'healthcare',
    phoneNumber: '+1 (800) 555-0199',
    email: 'contact@stjudeclinic.care',
    address: '1400 Health Plaza Blvd, Suite 300, Boston, MA',
    timezone: 'America/New_York',
    businessHours: {
      monday: { open: '08:00', close: '18:00', isOpen: true },
      tuesday: { open: '08:00', close: '18:00', isOpen: true },
      wednesday: { open: '08:00', close: '18:00', isOpen: true },
      thursday: { open: '08:00', close: '18:00', isOpen: true },
      friday: { open: '08:00', close: '17:00', isOpen: true },
      saturday: { open: '09:00', close: '14:00', isOpen: true },
      sunday: { open: '10:00', close: '14:00', isOpen: false },
    },
    plan: 'enterprise',
    minutesUsed: 428,
    minutesLimit: 2500,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'biz_realestate_02',
    name: 'Apex Prime Luxury Real Estate',
    slug: 'apex-prime-estates',
    industry: 'real_estate',
    phoneNumber: '+1 (888) 720-4321',
    email: 'concierge@apexprime.luxury',
    address: '9454 Wilshire Blvd, Beverly Hills, CA 90212',
    timezone: 'America/Los_Angeles',
    businessHours: {
      monday: { open: '09:00', close: '19:00', isOpen: true },
      tuesday: { open: '09:00', close: '19:00', isOpen: true },
      wednesday: { open: '09:00', close: '19:00', isOpen: true },
      thursday: { open: '09:00', close: '19:00', isOpen: true },
      friday: { open: '09:00', close: '19:00', isOpen: true },
      saturday: { open: '10:00', close: '17:00', isOpen: true },
      sunday: { open: '11:00', close: '16:00', isOpen: true },
    },
    plan: 'pro',
    minutesUsed: 215,
    minutesLimit: 1000,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'biz_auto_03',
    name: 'Precision Auto Works & Diagnostics',
    slug: 'precision-auto-works',
    industry: 'auto_repair',
    phoneNumber: '+1 (800) 412-8877',
    email: 'support@precisionautoworks.com',
    address: '2200 Motor Speedway Ave, Dallas, TX 75201',
    timezone: 'America/Chicago',
    businessHours: {
      monday: { open: '07:30', close: '18:00', isOpen: true },
      tuesday: { open: '07:30', close: '18:00', isOpen: true },
      wednesday: { open: '07:30', close: '18:00', isOpen: true },
      thursday: { open: '07:30', close: '18:00', isOpen: true },
      friday: { open: '07:30', close: '18:00', isOpen: true },
      saturday: { open: '08:00', close: '14:00', isOpen: true },
      sunday: { open: '09:00', close: '13:00', isOpen: false },
    },
    plan: 'pro',
    minutesUsed: 310,
    minutesLimit: 1000,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'biz_dental_04',
    name: 'Lumina Dental Studio',
    slug: 'lumina-dental-studio',
    industry: 'dental',
    phoneNumber: '+1 (800) 902-1200',
    email: 'care@luminadental.com',
    address: '500 Fifth Avenue, Floor 14, New York, NY 10110',
    timezone: 'America/New_York',
    businessHours: {
      monday: { open: '08:30', close: '17:30', isOpen: true },
      tuesday: { open: '08:30', close: '17:30', isOpen: true },
      wednesday: { open: '08:30', close: '17:30', isOpen: true },
      thursday: { open: '08:30', close: '17:30', isOpen: true },
      friday: { open: '08:30', close: '16:00', isOpen: true },
      saturday: { open: '09:00', close: '13:00', isOpen: true },
      sunday: { open: '09:00', close: '13:00', isOpen: false },
    },
    plan: 'starter',
    minutesUsed: 89,
    minutesLimit: 500,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'agent_health_01',
    businessId: 'biz_healthcare_01',
    name: 'Dr. Maya (Main Inbound AI)',
    role: 'Clinical Receptionist & Triage',
    type: 'inbound',
    voiceId: 'alloy',
    voiceSpeed: 1.0,
    voicePitch: 1.0,
    systemPrompt: INDUSTRIES.healthcare.defaultPrompt,
    greetingMessage: INDUSTRIES.healthcare.defaultGreeting,
    status: 'active',
    forwardingPhone: '+1 (800) 555-0100',
    maxCallDurationSeconds: 600,
    autoBookAppointments: true,
    collectLeadInfo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'agent_health_02',
    businessId: 'biz_healthcare_01',
    name: 'Patient Recall & Reminder Bot',
    role: 'Outbound Appointment Follow-up',
    type: 'outbound',
    voiceId: 'nova',
    voiceSpeed: 1.05,
    voicePitch: 1.0,
    systemPrompt: 'You are an outbound AI receptionist confirming upcoming lab tests and annual doctor visits with existing patients.',
    greetingMessage: 'Hello! This is Maya from St. Jude Clinic calling to confirm your upcoming appointment tomorrow. Do you have a quick moment?',
    status: 'active',
    forwardingPhone: '+1 (800) 555-0100',
    maxCallDurationSeconds: 300,
    autoBookAppointments: true,
    collectLeadInfo: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'agent_realestate_01',
    businessId: 'biz_realestate_02',
    name: 'Sophia Luxury Concierge',
    role: 'VIP Inbound Lead Qualifier',
    type: 'inbound',
    voiceId: 'shimmer',
    voiceSpeed: 1.0,
    voicePitch: 1.02,
    systemPrompt: INDUSTRIES.real_estate.defaultPrompt,
    greetingMessage: INDUSTRIES.real_estate.defaultGreeting,
    status: 'active',
    forwardingPhone: '+1 (888) 720-4300',
    maxCallDurationSeconds: 900,
    autoBookAppointments: true,
    collectLeadInfo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'agent_auto_01',
    businessId: 'biz_auto_03',
    name: 'Alex Service Advisor',
    role: 'Front Desk & Diagnostics Booking',
    type: 'inbound',
    voiceId: 'echo',
    voiceSpeed: 1.0,
    voicePitch: 0.98,
    systemPrompt: INDUSTRIES.auto_repair.defaultPrompt,
    greetingMessage: INDUSTRIES.auto_repair.defaultGreeting,
    status: 'active',
    forwardingPhone: '+1 (800) 412-8800',
    maxCallDurationSeconds: 600,
    autoBookAppointments: true,
    collectLeadInfo: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'agent_dental_01',
    businessId: 'biz_dental_04',
    name: 'Chloe Dental Assistant',
    role: 'Patient Care & Appointment Desk',
    type: 'inbound',
    voiceId: 'fable',
    voiceSpeed: 1.0,
    voicePitch: 1.0,
    systemPrompt: INDUSTRIES.dental.defaultPrompt,
    greetingMessage: INDUSTRIES.dental.defaultGreeting,
    status: 'active',
    forwardingPhone: '+1 (800) 902-1250',
    maxCallDurationSeconds: 600,
    autoBookAppointments: true,
    collectLeadInfo: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  { id: 'srv_1', businessId: 'biz_healthcare_01', name: 'General Practitioner Consultation', description: 'Comprehensive physical evaluation, vitals, prescription refills.', durationMinutes: 30, price: 95, category: 'Outpatient', isActive: true },
  { id: 'srv_2', businessId: 'biz_healthcare_01', name: 'Cardiology Specialist Consult', description: 'ECG review, hypertension management, heart health.', durationMinutes: 45, price: 180, category: 'Specialist', isActive: true },
  { id: 'srv_3', businessId: 'biz_healthcare_01', name: 'Complete Blood & Metabolic Panel', description: 'Fasting lipid, glucose, CBC, kidney and liver panels.', durationMinutes: 15, price: 65, category: 'Diagnostics', isActive: true },
  { id: 'srv_4', businessId: 'biz_healthcare_01', name: 'Pediatric Wellness Checkup', description: 'Vaccinations, developmental milestones, physical growth.', durationMinutes: 30, price: 85, category: 'Pediatrics', isActive: true },

  { id: 'srv_5', businessId: 'biz_realestate_02', name: 'Private Luxury Villa Showing', description: 'Exclusive 1-on-1 walkthrough with head broker.', durationMinutes: 60, price: 0, category: 'Showings', isActive: true },
  { id: 'srv_6', businessId: 'biz_realestate_02', name: 'Penthouse VIP Tour', description: 'Full property overview and architectural appraisal.', durationMinutes: 45, price: 0, category: 'Showings', isActive: true },
  { id: 'srv_7', businessId: 'biz_realestate_02', name: 'Home Valuation & Seller Strategy', description: 'Market comparative analysis and listing strategy.', durationMinutes: 30, price: 0, category: 'Consultation', isActive: true },

  { id: 'srv_8', businessId: 'biz_auto_03', name: 'Synthetic Oil & Filter Service', description: 'Full synthetic oil up to 5qts, OEM filter, 21-point check.', durationMinutes: 45, price: 89, category: 'Maintenance', isActive: true },
  { id: 'srv_9', businessId: 'biz_auto_03', name: 'Brake Inspection & Pad Replacement', description: 'Front/rear ceramic brake pads with rotor resurfacing.', durationMinutes: 60, price: 149, category: 'Brakes', isActive: true },
  { id: 'srv_10', businessId: 'biz_auto_03', name: 'Full Computer Diagnostics (OBD-II)', description: 'Engine check light scan, electrical circuit diagnostic.', durationMinutes: 30, price: 110, category: 'Diagnostics', isActive: true },

  { id: 'srv_11', businessId: 'biz_dental_04', name: 'Comprehensive Exam & Deep Cleaning', description: 'Oral cancer screening, ultrasonic scaling, polish.', durationMinutes: 45, price: 120, category: 'Hygiene', isActive: true },
  { id: 'srv_12', businessId: 'biz_dental_04', name: 'Invisalign 3D Smile Assessment', description: 'iTero 3D digital scan & clear aligner preview.', durationMinutes: 30, price: 0, category: 'Cosmetic', isActive: true },
];

export const INITIAL_KNOWLEDGE: KnowledgeItem[] = [
  {
    id: 'k_1',
    businessId: 'biz_healthcare_01',
    category: 'urgent_protocol',
    question: 'How do you handle emergency medical calls?',
    answer: 'If the caller mentions chest pain, severe shortness of breath, sudden numbness, or heavy bleeding, immediately instruct them to dial 911 or head to the emergency room at 1400 Health Plaza.',
    keywords: ['emergency', 'urgent', '911', 'chest pain', 'ambulance'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'k_2',
    businessId: 'biz_healthcare_01',
    category: 'pricing',
    question: 'What health insurances are in-network?',
    answer: 'We accept Blue Cross Blue Shield, Aetna, Cigna, Medicare Part B, and UnitedHealthcare. Copays typically range from $20 to $40.',
    keywords: ['insurance', 'coverage', 'aetna', 'medicare', 'copay'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'k_3',
    businessId: 'biz_healthcare_01',
    category: 'location',
    question: 'Where is the clinic located and where do I park?',
    answer: 'We are at 1400 Health Plaza Blvd, Suite 300, Boston. Complimentary patient parking is available in Garage B on level 2.',
    keywords: ['address', 'directions', 'parking', 'location', 'garage'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'k_4',
    businessId: 'biz_realestate_02',
    category: 'policy',
    question: 'What is required prior to scheduling a private tour of high-value estates?',
    answer: 'For listings exceeding $5,000,000, we require a quick pre-qualification letter or proof of funds prior to dispatching our private showing specialist.',
    keywords: ['proof of funds', 'tour', 'viewing', 'qualification', 'luxury'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'k_5',
    businessId: 'biz_auto_03',
    category: 'policy',
    question: 'Can I drop my car off after hours?',
    answer: 'Yes! We offer a 24/7 Secure Key Drop Box located on the right side of bay door #1. Simply fill out the yellow envelope with your phone and keys.',
    keywords: ['drop off', 'night drop', 'key box', 'after hours'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_101',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    serviceId: 'srv_1',
    serviceName: 'General Practitioner Consultation',
    customerName: 'Sarah Jenkins',
    customerPhone: '+1 (617) 492-8812',
    customerEmail: 'sarah.j@example.com',
    startTime: new Date(Date.now() + 2 * 3600000).toISOString(),
    endTime: new Date(Date.now() + 2.5 * 3600000).toISOString(),
    status: 'confirmed',
    notes: 'Seasonal allergies and annual routine prescription renewal.',
    bookedVia: 'ai_voice',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'apt_102',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    serviceId: 'srv_2',
    serviceName: 'Cardiology Specialist Consult',
    customerName: 'Marcus Vance',
    customerPhone: '+1 (617) 883-2940',
    customerEmail: 'mvance@techcorp.io',
    startTime: new Date(Date.now() + 26 * 3600000).toISOString(),
    endTime: new Date(Date.now() + 26.75 * 3600000).toISOString(),
    status: 'confirmed',
    notes: 'Follow-up for mild arrhythmia. Requested Dr. Sterling.',
    bookedVia: 'ai_voice',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'apt_103',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    serviceId: 'srv_3',
    serviceName: 'Complete Blood & Metabolic Panel',
    customerName: 'Elena Rostova',
    customerPhone: '+1 (617) 555-4011',
    customerEmail: 'elena.rostova@gmail.com',
    startTime: new Date(Date.now() + 50 * 3600000).toISOString(),
    endTime: new Date(Date.now() + 50.25 * 3600000).toISOString(),
    status: 'pending',
    notes: 'Fasting blood test requested for 9:00 AM.',
    bookedVia: 'web_portal',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'apt_104',
    businessId: 'biz_realestate_02',
    agentId: 'agent_realestate_01',
    serviceId: 'srv_5',
    serviceName: 'Private Luxury Villa Showing',
    customerName: 'David Sterling',
    customerPhone: '+1 (310) 902-8811',
    customerEmail: 'd.sterling@capitalgroup.com',
    startTime: new Date(Date.now() + 28 * 3600000).toISOString(),
    endTime: new Date(Date.now() + 29 * 3600000).toISOString(),
    status: 'confirmed',
    notes: 'Interested in Beverly Hills estate listing #BH-8840. Pre-approved for $7.5M.',
    bookedVia: 'ai_voice',
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'apt_105',
    businessId: 'biz_auto_03',
    agentId: 'agent_auto_01',
    serviceId: 'srv_8',
    serviceName: 'Synthetic Oil & Filter Service',
    customerName: 'Robert Gomez',
    customerPhone: '+1 (214) 774-0199',
    startTime: new Date(Date.now() + 4 * 3600000).toISOString(),
    endTime: new Date(Date.now() + 4.75 * 3600000).toISOString(),
    status: 'confirmed',
    notes: '2022 Ford F-150. Requested tire rotation check as well.',
    bookedVia: 'ai_voice',
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_1',
    businessId: 'biz_healthcare_01',
    name: 'Emily Watson',
    phone: '+1 (617) 332-9011',
    email: 'emily.w@healthmail.com',
    status: 'qualified',
    score: 92,
    source: 'AI Phone Call',
    interest: 'Family Medicine & Pediatrics',
    budget: '$500/mo family plan',
    aiSummary: 'Relocating to Boston next month. Looking for a primary physician for husband and 2 children.',
    lastContactAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'lead_2',
    businessId: 'biz_healthcare_01',
    name: 'Arthur Pendelton',
    phone: '+1 (617) 880-1294',
    email: 'pendelton.a@lawfirm.com',
    status: 'new',
    score: 68,
    source: 'AI Phone Call',
    interest: 'Executive Physical Exam',
    budget: '$1,200',
    aiSummary: 'Inquired about comprehensive executive cardiovascular health screening.',
    lastContactAt: new Date(Date.now() - 14 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 3600000).toISOString(),
  },
  {
    id: 'lead_3',
    businessId: 'biz_realestate_02',
    name: 'Julian Vance',
    phone: '+1 (310) 555-8910',
    email: 'jvance@venture.io',
    status: 'tour_scheduled',
    score: 96,
    source: 'AI Phone Call',
    interest: 'Bel Air Modern Architectural Villa',
    budget: '$8,500,000',
    aiSummary: 'All-cash tech executive buyer seeking private gated residence with tennis court and panoramic city views.',
    lastContactAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'lead_4',
    businessId: 'biz_auto_03',
    name: 'Daniel Carter',
    phone: '+1 (214) 890-4411',
    status: 'follow_up',
    score: 75,
    source: 'AI Phone Call',
    interest: 'Audi S5 Transmission Flush & Tuning',
    budget: '$900',
    aiSummary: 'Wants performance fluid upgrade. Requested callback with technician time slot.',
    lastContactAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];

export const INITIAL_CALLS: CallLog[] = [
  {
    id: 'call_1',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    agentName: 'Dr. Maya (Main Inbound AI)',
    callerName: 'Sarah Jenkins',
    callerPhone: '+1 (617) 492-8812',
    direction: 'inbound',
    durationSeconds: 142,
    status: 'completed',
    sentiment: 'positive',
    aiSummary: 'Patient called inquiring about booking an appointment for allergy symptoms. AI verified provider availability, gathered patient details, and booked General Consultation slot.',
    outcome: 'Appointment Booked',
    actionTaken: 'Created appointment #apt_101',
    cost: 0.042,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    transcript: [
      { speaker: 'ai', text: 'Thank you for calling St. Jude Regional Clinic. My name is Maya, your AI health assistant. How may I assist your medical care today?', timestamp: 0 },
      { speaker: 'caller', text: 'Hi Maya, I have been having bad allergy flare-ups and need to see a doctor this afternoon if possible.', timestamp: 5 },
      { speaker: 'ai', text: 'I would be glad to help you schedule that right away. We have an opening for a General Practitioner Consultation today at 2:00 PM. Would that work for you?', timestamp: 12 },
      { speaker: 'caller', text: 'Yes, 2:00 PM is perfect! My name is Sarah Jenkins.', timestamp: 18 },
      { speaker: 'ai', text: 'Wonderful, Sarah! May I have your phone number and email address to send the appointment confirmation?', timestamp: 24 },
      { speaker: 'caller', text: 'My number is 617-492-8812 and email is sarah.j@example.com.', timestamp: 31 },
      { speaker: 'ai', text: 'I have confirmed your appointment with Dr. Harris for today at 2:00 PM. You will receive an SMS and email with arrival guidelines. Is there anything else I can assist you with?', timestamp: 38 },
      { speaker: 'caller', text: 'That was so quick, thank you Maya!', timestamp: 46 },
      { speaker: 'ai', text: 'You are very welcome, Sarah! We look forward to seeing you. Take care and goodbye!', timestamp: 50 },
    ],
  },
  {
    id: 'call_2',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    agentName: 'Dr. Maya (Main Inbound AI)',
    callerName: 'Marcus Vance',
    callerPhone: '+1 (617) 883-2940',
    direction: 'inbound',
    durationSeconds: 185,
    status: 'completed',
    sentiment: 'positive',
    aiSummary: 'Caller inquired about cardiology specialists and insurance coverage. AI confirmed BlueCross acceptance and scheduled follow-up consult.',
    outcome: 'Appointment Booked',
    actionTaken: 'Created appointment #apt_102',
    cost: 0.055,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    transcript: [
      { speaker: 'ai', text: 'Thank you for calling St. Jude Regional Clinic. My name is Maya, your AI health assistant. How may I assist your medical care today?', timestamp: 0 },
      { speaker: 'caller', text: 'Hello, do you accept BlueCross BlueShield for cardiology consults?', timestamp: 4 },
      { speaker: 'ai', text: 'Yes, Marcus! St. Jude Clinic is an in-network provider with BlueCross BlueShield. Cardiology specialist evaluations typically have a standard specialist copay.', timestamp: 10 },
      { speaker: 'caller', text: 'Great, can I book a cardiology checkup with Dr. Sterling?', timestamp: 17 },
      { speaker: 'ai', text: 'Certainly! I have scheduled your Cardiology Assessment for tomorrow at 10:00 AM with Dr. Sterling. A confirmation has been generated.', timestamp: 24 },
    ],
  },
  {
    id: 'call_3',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    agentName: 'Dr. Maya (Main Inbound AI)',
    callerName: 'Robert Keller',
    callerPhone: '+1 (617) 901-4455',
    direction: 'inbound',
    durationSeconds: 98,
    status: 'transferred',
    sentiment: 'neutral',
    aiSummary: 'Caller reported acute severe pain. AI evaluated protocol, advised emergency safety, and transferred call directly to emergency nurse triage line.',
    outcome: 'Transferred to Human Nurse',
    actionTaken: 'Transferred to +1 (800) 555-0100',
    transferredTo: '+1 (800) 555-0100',
    cost: 0.029,
    createdAt: new Date(Date.now() - 20 * 3600000).toISOString(),
    transcript: [
      { speaker: 'ai', text: 'Thank you for calling St. Jude Regional Clinic. My name is Maya, how may I assist you today?', timestamp: 0 },
      { speaker: 'caller', text: 'I am experiencing sudden acute dizziness and chest pressure right now.', timestamp: 4 },
      { speaker: 'ai', text: 'Robert, based on your symptoms, I am immediately connecting you to our emergency charge nurse on duty right now. Please remain on the line.', timestamp: 9 },
    ],
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp_1',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_02',
    name: 'Spring Flu Shot & Wellness Reminder',
    description: 'Automated outbound voice campaign to senior patients for seasonal immunization booking.',
    status: 'running',
    totalLeads: 150,
    callsCompleted: 94,
    appointmentsBooked: 41,
    scheduledFor: new Date().toISOString(),
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'camp_2',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_02',
    name: 'Post-Op Patient Satisfaction & Health Check',
    description: 'Check in on outpatient surgery patients 48 hours post-procedure.',
    status: 'completed',
    totalLeads: 45,
    callsCompleted: 45,
    appointmentsBooked: 8,
    scheduledFor: new Date(Date.now() - 5 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

export const INITIAL_WIDGET_CONFIGS: Record<string, WidgetConfig> = {
  biz_healthcare_01: {
    id: 'w_health_1',
    businessId: 'biz_healthcare_01',
    agentId: 'agent_health_01',
    title: 'St. Jude AI Health Desk',
    subtitle: 'Book appointments & ask medical care questions 24/7',
    primaryColor: '#e11d48',
    buttonText: 'Talk to Clinic Receptionist',
    greeting: 'Hi! I’m Maya, your AI clinic receptionist. How may I assist you today?',
    position: 'bottom-right',
    isActive: true,
  },
  biz_realestate_02: {
    id: 'w_real_1',
    businessId: 'biz_realestate_02',
    agentId: 'agent_realestate_01',
    title: 'Apex Prime VIP Concierge',
    subtitle: 'Schedule luxury tours & speak with AI concierge',
    primaryColor: '#e11d48',
    buttonText: 'Speak with Real Estate Agent',
    greeting: 'Welcome to Apex Prime. How can I help you find your dream estate?',
    position: 'bottom-right',
    isActive: true,
  },
  biz_auto_03: {
    id: 'w_auto_1',
    businessId: 'biz_auto_03',
    agentId: 'agent_auto_01',
    title: 'Precision Auto Service AI',
    subtitle: 'Instant diagnostics & repair scheduling',
    primaryColor: '#e11d48',
    buttonText: 'Book Service with AI',
    greeting: 'Hey! Need an oil change, brakes, or diagnostic service booked?',
    position: 'bottom-right',
    isActive: true,
  },
  biz_dental_04: {
    id: 'w_dental_1',
    businessId: 'biz_dental_04',
    agentId: 'agent_dental_01',
    title: 'Lumina Dental Studio AI',
    subtitle: 'Schedule cleanings & cosmetic consults',
    primaryColor: '#e11d48',
    buttonText: 'Chat with Dental AI',
    greeting: 'Welcome to Lumina Dental Studio. How can we make you smile today?',
    position: 'bottom-right',
    isActive: true,
  },
};